# Created 2021-01-17 Sun 21:08
#+title: MarColumn: open source vs. commercieel
#+author: Marc van der Sluys

Deze column gaat over mijn gebruik van Linux en Free Open Source Software (FOSS).  Deze maand wil ik mijn visie op het verschil tussen commerciële software en FOSS uiteenzetten.  De twee zijn niet zo verschillend als ze misschien lijken - beide beogen optimale software.  Een belangrijk verschil is echter de variabele die wordt geoptimaliseerd.

Bij open-sourcesoftware is die variabele kwaliteit.  FOSS ontstaat typisch wanneer een handige programmeur een stukje software nodig heeft dat nog niet bestaat, of alleen in onvoldoende kwaliteit.  Zij maakt die software dus zelf en is pas klaar wanneer de kwaliteit hoog genoeg is.  Het programma moet niet alleen het goede antwoord geven, maar ook bijvoorbeeld stabiel, snel, veilig en efficiënt zijn.  Daarnaast wil onze programmeur optimale controle en flexibiliteit.  Maar ze doorziet ook dat anderen mogelijk dezelfde wensen hebben als zij.  En dus besluit zij om haar code te delen met de wereld door deze online te zetten.  Het resultaat is een stukje software dat zo goed is dat je het zelf zou willen gebruiken.

Bij commerciële software heet die optimalisatievariabele winst.  Het doel van de software is om zoveel mogelijk geld te verdienen per gemaakte eenheid kwaliteit.  Meer kwaliteit kost immers meer werk, en ook een commerciële programmeur wil wel slapend rijk worden.  De meeste klanten merken toch niet dat de veiligheid niet waterdicht is of weten niet dat er alternatieven bestaan die je niet steeds opnieuw hoeft op te starten.  Misschien heeft de klant zelfs geen keuze, doordat dit de enige software is voor deze hardware.  En als de klant net iets anders zou willen met de software dan wat de programmeur had bedacht, heeft de eerste pech.  Het commerciële doel van zoveel mogelijk geld per eenheid kwaliteit kun je ook uitdrukken als zo min mogelijk kwaliteit leveren per betaalde euro.  Goede commerciële software is dus per definitie de kwalitatief laagwaardigste software die je voor een euro kunt krijgen.

De reden waarom ik graag open-sourcesoftware gebruik is dat deze vaak beter is dan commerciële software.  Mijn programma's rekenen bijvoorbeeld circa 100.000 keer sneller dan Excel.  Mijn systeem lijkt stabieler dan dat van collega's, al moest ik deze maand mijn laptop rebooten, en in mei ook al.  Het meest bizarre verschil zit in de controle en flexibiliteit.  Mijn laptop update zichzelf als ik deze 's nachts aan laat staan, maar mijn collega's mogen soms 's avonds niet naar huis van hun laptop omdat die een update doet en niet uitgeschakeld wil worden!  Ook hoor ik regelmatig van studenten dat ze eigenlijk iets anders wilden doen, maar dat de software dat niet toeliet.  Bij commerciële software lijkt het dus vaak dat de computer bepaalt wat de gebruiker mag doen.  In mijn wereld is dat precies andersom.

Marc van der Sluys.
