# Created 2021-11-05 Sun 09:39
#+title: MarColum: De Windows-Mac-Linux experience
#+author: Marc van der Sluys

Ik heb in mijn leven tot nu toe computersystemen gebruikt die draaiden op DOS/Windows, macOS of Linux. Uiteindelijk ben ik toch bij Linux blijven plakken. Een kans van 98 %, zou je zeggen...

Mijn gebruik van DOS/Windows dateert van een ver verleden, toen monitoren nog dieper waren dan breed of hoog, het een luxe was als je 5,25" én 3,5" diskettes kon lezen en ik nog geen flauw idee had waar de MS voor DOS voor stond. Kleurenschermen waren er nog niet, BBS-en wel en veel van de software die ik gebruikte waren waarschijnlijk illegale kopiën die via mijn 2400-baud modem binnenkwamen. Het installeren van nieuwe versies van Windows werd steeds meer gedoe en bij een van de laatste keren (98 of 2000) kan ik me herinneren dat er tijdens de installatie meermaals moest worden gereboot. Na een van die reboots kon de installer de CD-ROM- drive niet meer vinden. Vertwijfeld schelden en schreeuwen dat daarvandaan al die tijd werd geïnstalleerd bleek niet te helpen...

Linux ging ik steeds meer gebruiken tegen het einde van mijn studie (ten koste van UNIX). Toen ik als promovendus een eigen PC met Red Hat kreeg, kreeg ik ook een iets beter idee over hoe zo'n (file)systeem was ingericht. Maar nadat het zelf installeren van Red Hat op een laptop een paar keer was uitgelopen in een falende X server aan het einde, kon ik al leen de tip van een collega volgen en Mandrake installeren. Dat werkte wel, maar ik had geen idee waardoor. Echt Linux doorgronden kwam pas nadat ik Gentoo leerde kennen, zo als in een eerdere MarColumn vermeld.

Toen ik in Chicago kwam werken kon ik kiezen uit een Mac. Nadat ik de doos en MacBook opende, kwam de vraag of ik met dit draadloze netwerk wilde verbinden. Take that, Micro$oft Can’t-find-your- CD-ROM Windhoos! Het werkt allemaal en macOS is erg gelikt, maar als het nèt niet zo werkt als je wilt, of jouw smaak afwijkt van die van Steve Jobs, loop je tegen de grenzen aan. Nadat ik het OS een paar maanden had gebruikt en steeds meer geporte GNU software draaide, heb ik maar besloten om Linux te installeren op mijn MacBook.

Een voordeel van besturingssystemen gebaseerd op de Linuxkernel is dat er zoveel smaken zijn. Momenteel kun je kiezen uit circa 300 varianten, waarvan er circa 100 actief zijn (ik neem aan de meer succesvolle gevallen, dus negeer de rest). De kans dat er een bij zit die voldoet aan je eisen en wensen is daarmee aanzienlijk. Als je macOS wilt kun je kiezen uit Apple, en bij Windows uit Microsoft — een 100 keer kleinere kans dat het bij je past. Dat lijkt op stemmen in Noord Korea; hoe groot is de kans dat die ene partij jouw wensen vertegenwoordigt? Geef mij maar een OS met keuze uit honderd smaken en een politiek systeem met keuze uit meer dan één of twee partijen.

De prijs is voor mij ook belangrijk: voor €159 heb je de Pro versie van Microsoft Windows en voor €119 een uitgeklede Home variant.[fn:1] Dit zijn beperkte versies waarmee je je computer omtovert in een soort typemachine. Voeg nog € 65-139 toe om een jaar gebruik te mogen maken van de bijbehorende typesoftware [fn:2] en €25-45 per jaar om je typemachine virusvrij te houden.[fn:3] Bij Apple is het onderscheid tussen de prijzen van soft- en hardware vager, maar als de verhouding hetzelfde is als bij Windows kost het OS circa € 200. De prijs van MS Office zal waarschijnlijk gelijk zijn aan die voor Windows. De meeste Linux OSsen zijn gratis. MS Office is slechts beschikbaar voor 2 % van de besturingssystemen die ik hier beschouw, maar LibreOffice biedt dezelfde functionaliteit en is verkrijgbaar voor 100 % daarvan, zodat je ook bestanden met anderen kunt uitwisselen.

Maar bovenstaande vergelijking is flauw - bij Windows en macOS krijg je immers een uitgeklede versie, terwijl dat bij de Linux OSsen niet zo is. Bij Apple kun je je typemachine voor slechts $ 20 opvoeren tot een server zodat je je Mac zelf mag configureren(!) [fn:4], bij Microsoft kost de serverversie $ 1000-$ 6000, of $ 240-$ 1500 per jaar. Ik ben een poweruser en ook baas zijn in eigen PC is een van mijn eisen — bij mijn vorige baan op de hogeschool zaten mijn Windows-collega’s ’s avonds regelmatig te wachten tot ze naar huis mochten van Microsoft, dat een Windowsupdate belangrijker vond dan het halen van de trein. Microsoft zou jóu moeten betalen om Windows te gebruiken!

Met Linux bespaar ik ook op de kosten van hardware. De laptop waarop ik dit type kocht ik tweedehands (€ 300), is acht jaar oud en was waarschijnlijk te traag voor Windows. Met Gentoo Linux is dat geen probleem en hoef ik dus nooit meer een nieuwe laptop te kopen! Dat is ook nog duurzaam.

Kortom, mijn reis langs drie soorten OS bracht me bij (Gentoo) Linux: ik heb keuze, ik kan meer dan alleen typen, ik bespaar € 1500 per drie jaar aan nieuwe hardware, honderden euro’s per jaar aan software en tijd doordat ik mijn trein wél haal. OK, mijn laptop is misschien niet zo shiny, maar daar geef ik niet veel om. En ík bepaal wat mijn computer doet, niet andersom!


Marc van der Sluys.

[fn:1] https://www.paradigit.nl/software/microsoft-windows/ 

[fn:2] https://www.paradigit.nl/software/microsoft-office/ 

[fn:3] https://www.paradigit.nl/software/antivirus-en-beveiliging/ 

[fn:4] https://www.apple.com/macos/server/ 
