# Created 2021-11-28 Sun 08:49
#+title: MarColumn: Gentoo Linux
#+author: Marc van der Sluys

OK, misschien ben ik een control freak.  Of een nerd.  Of allebei.  Maar op míjn laptop alleen nog Gentoo Linux!

Wat bedoel je dat de vorige versie van dit package niet meer beschikbaar is?  Na de update werkt dit programma niet meer zoals ik wil, dus ik wil nu terug en dan wachten op de volgende update.  En het is hartstikke leuk dat dit binary package is gecompileerd voor x86-64-processoren, maar de mijne is een x86-64 Ivy Bridge en dus ik wil een package dat dáárvoor is geoptimaliseerd en gebruik maakt van de specifieke instructies die deze processor sneller maakt.  In Nederland zijn er wegen waar de maximumsnelheid 30 km/uur is, maar dat betekent toch niet dat dit dus overál de limiet is?  En hoe zet ik bluetoothondersteuning voor deze software uit?  Ik heb helemaal geen bluetooth hardware, dus ik wil die kloktikken dat geheugen besparen.  En ik heb die static libraries van gcc nodig, waarom is er bij deze Linux-distributie geen optie om die te installeren?  Als ik geen keuzemogelijkheden zou willen in mijn leven kocht ik wel een Windoos en verhuisde ik naar Noord Korea.

Ik gebruik dus Gentoo Linux, niet toevallig genoemd naar de snelst zwemmende pinguïn.  Je kunt zo'n beetje alles tweaken en aanpassen naar je smaak, als je maar een teksteditor kunt gebruiken (waarover in een latere column meer).  Ik heers als een soort god over het universumpje dat mijn laptop is, en zie dat het goed is.  Bwahahaha!  Op een Gentoosysteem wordt vrijwel alles van source gecompileerd, en is de software dus geoptimaliseerd voor jouw CPU en jouw systeem.  Door middel van USE flags worden alleen die onderdelen van ieder package geïnstalleerd die je wilt; geen ondersteuning voor Gnome als je KDE/Plasma gebruikt en helemaal geen grafische desktop op een headless server.  Maar wel keuze uit 13 desktop environments.  Logt mijn partner liever in op Gnome dan KDE, dan installeer ik ze gewoon allebei en kunnen we kiezen.  Gentoo ondersteunt momenteel een stuk of 15 architecturen, biedt standaard een paar versies aan van ieder package, en de meeste packages zijn dus in detail configurabel door USE flags die ik aan of uit kan zetten.  Zo zijn er momenteel 10 verschillende versies van de gcc compiler suite beschikbaar (waarvan er zes tegelijkertijd geïnstalleerd kunnen zijn) voor 14 CPU's en met 30 USE flags.  Daarmee zijn er ruim 150 miljard verschillende versies van gcc te installeren met Gentoo.  Daar kan Arch Linux nog een puntje aan zuigen!

Toen ik in Chicago werkte had ik twee collega's die Gentoo gebruikten en een derde die het wilde leren.  Ik was inmiddels ook wel weer uitgekeken op m'n Mac (waarover in een latere column ook meer) en pikte dus aan.  Tjonge, wat eng!  Start van het live-medium (toen een cd) en je krijgt een bash (of zsh) prompt.  Veel succes!  Gelukkig had ik m'n collega's en de geweldige Gentoowebsite met de te nemen stappen en veel uitleg.  Dat laatste is belangrijk, want wat heb ik veel geleerd!  Eerder kwam ik wel eens tegen dat ik m'n kernel opnieuw moest compileren, en mijn reactie was (noodgedwongen) dat ik dit feature ook weer niet zó graag wilde.  Maar sinds die eerste Gentoo-installatie draai ik daar mijn hand niet meer voor om.  Verbazingwekkend hoeveel hardware wordt ondersteund door de Linux kernel, én dat je dat als mens (nou ja, inmiddels halfgod) toch nog een soort van kunt overzien.  Die eerste installatie duurde een dag en een nacht (de nacht was nodig om KDE te compileren) en een systeemupdate kost relatief veel tijd (dus dat doe ik nog steeds 's nachts) en soms moet je wat pielen als een package niet wil compileren.  Maar iedere twee jaar het hele systeem opnieuw installeren is met deze rolling release niet nodig.  Het overzetten van je systeem op een nieuwe laptop is relatief eenvoudig: ik heb Gentoo geïnstalleerd op mijn nieuwe Nijmeegse laptop vanuit Canada (met hulp van een student die de cd erin deed en mij het ip-adres mailde).  En dat pielen is het allemaal waard om de absolute macht over mijn universum te verkrijgen.  Bwahahahaha!
