# Created 2021-07-25 Sun 15:09
#+title: FOSS op scholen
#+author: Marc van der Sluys

Ik werk al een aantal jaar op een hogeschool in het oosten van Nederland.  Officieel ben ik onderzoeker bij het lectoraat Duurzame energie, waar ik voornamelijk met software werk: het modelleren van de opbrengst ontworpen systemen, het bouwen van (autonome) meetsystemen en het analyseren van de data.  Dat zijn dingen die ik leuk vind om te doen, en waar ik volgens mij ook best goed in ben.  Daarnaast heb ik een tijdje lesgegeven in het vak Operating systems, een tweedejaars vak waarin de studenten van de opleiding Embedded systems engineering (voorheen onderdeel van Elektrotechniek) leren om low-level C-programma's te schrijven die nauw samenwerken met het GNU/Linux besturingssysteem (OS).  Dat was leuk om te doen, en ook spannend, want de helft van de stof kende ik van het gebruik van de Bash shell, maar de andere helft moest ik leren.  Ik heb ook van de gelegenheid gebruik gemaakt om in het kader van de algemene ontwikkeling en professionalisering ook zaken als Bash, emacs, git en GitHub in het curriculum te stoppen.  Oh ja, en de studenten moeten tegenwoordig als eindopdracht van scratch een Arch Linux-systeem installeren en configureren op een Raspberry Pi.

Ik vond het echter ronduit schrikbarend dat dit zo'n beetje het enige onderdeel van hun opleiding was waar deze technische programmeurs in aanraking kwamen met Linux (veelal onder VMWare op hun laptop).  De meeste andere studenten hebben er waarschijnlijk nog nooit van gehoord.  Op open dagen wordt aan toekomstige studenten verkondigd dat ze in het hoger onderwijs onder andere leren om kritisch na te denken, maar op school wordt doorgaans impliciet medegedeeld dat er van de circa 100 veelgebruikte besturingssystemen er maar één echt in aanmerking komt voor gebruik.[fn:1]  Het gaat dan om dat van een van de mindere softwareleveranciers in Redmond, Washington, USA.[fn:2]  Dát mensen na een kritische vergelijking kiezen voor Windows als beste oplossing voor hun product is prima, maar dan moet de kennis die benodigd is voor een bewuste keuze wel aanwezig zijn.  Volgens mij is het de taak van de hogeschool om de studenten te leren kritisch nadenken zodat ze de juiste keuzes kunnen maken, niet om voor hen die keuzes te maken.

Onze studenten leren embedded apparaatjes bouwen.  Ik heb daar zelf weinig zicht op, maar denk aan aansturingen, meetapparatuur, enzovoorts.  Ik stel mezelf regelmatig voor dat een van onze studenten na haar of zijn studie als ZZP'er een apparaatje bouwt als wij vorig jaar hebben gekocht vanwege het vele thuiswerken.  Het meet onder andere de CO2 en het fijnstof, heeft display om dat weer te geven en verzamelt de data die via het netwerk kunnen worden uitgelezen.  Nuttig, want op mijn KDE-Plasma-desktop popt er een dingetje op wanneer er een raam open moet, of juist dicht.  De oud-student koopt de elektronica-onderdelen, bouw het apparaatje en wil ook nog wat winst maken.  Verkoopprijs: €150.  Oh ja, en €100 voor de licentie van het OS.  Een totale verkoopprijs van €250 dus.  Maar een oud-student van een hogeschool uit het wésten van ons land bouwt hetzelfde apparaatje en gebruikt een FOSS OS van €0.  Totale verkoopprijs dus €150.  Welk van deze twee ZZP'ers zal meer apparaatjes verkopen?  Hint: niet die van de hogeschool uit het oosten.

Voor de meeste andere vakken van deze studenten is de situatie ernstiger.  In veel gevallen komt de instructie niet verder dan hoe je een softwarepakket koopt (nu nog gratis via een onderwijslicentie, maar later, als je ZZP'er bent en alleen met dit pakket overweg kunt, lopen de kosten op) en gebruikt.  Maar we leren een elektrotechniekstudent toch ook niet hoe je een afwasmachine of stofzuiger koopt en bedient?  En de studie automotive is toch meer dan een serie rijlessen?  Waarom gelden er voor software andere regels?  En goh, hoe komt het toch dat er in Nederland zo weinig software-ontwikkelaars zijn dat onze overheid haar staatsgeheimen beheert op systemen die feitelijk worden beheerd door buitenlandse commerciële bedrijven met banden met hún overheid?

Ik noemde hierboven de impliciete mededeling van onze school dat er maar één serieuze softwareleverancier is.  Dat klinkt erg vreemd maar is nog niet zo vreemd als hoe dit komt.  Dit heeft te maken met de ICT-systemen op onze hogeschool.  Voor iedere toepassing moet er kritisch worden gekeken naar wat de beste softwareleverancier is om de software van te kopen.  Want software is altijd iets dat je koopt.  Voor de besturingssystemen van onze laptops is die beste leverancier Microsoft.  Voor Office-pakketten is dat Microsoft.[fn:3]  Voor emails het Microsoft.[fn:3],[fn:4]  En voor agendabeheer kwam Microsoft als beste uit de bus.[fn:3]  Het interne systeem om gegevens van medewerkers bij te houden wordt geleverd door Microsoft.  Declaratiesoftware: Microsoft.  Het lesrooster bekijken?  U kunt het vast raden.  Lesinformatie aan studenten aanbieden?  Right ho!  Vergaderen in coronatijd?  Teams, gemaakt door ... inderdaad.[fn:5]

Mocht het u nog niet zijn opgevallen, het vreemde hieraan is dat Microsoft hier steevast als "beste" uit de bus komt, ook als je daardoor met de emailtoepassing geen emails meer kunt ontvangen of verzenden en je met de agendatoepassing je agenda niet meer kunt beheren.  Het systeem waarmee wij het onderwijsmateriaal delen met studenten is ook erg ... interessant.  Bij mijn nieuwe vak over zonne-energie werd het dictaat nogal vaak geüpdatet.  Meerdere keren per week moest ik met de hand naar de webpagina browsen (die je alleen kunt vinden als je de URL hebt, zoeken op je eigen vak werkt niet) en een nieuwe PDF uploaden.  Maar dat kan niet, want dat bestand bestaat al.  Eerst verwijderen dus.  Maar dat kan ook niet, want het wordt genoemd in de tekst.  Dus eerst de naam uit de tekst halen, opslaan, het oude bestand verwijderen, het nieuwe bestand op je computer opzoeken en uploaden, de bestandsnaam weer in tekst zetten, nieuwe datum erachter typen, opslaan, en testen of je geen typefout hebt gemaakt.  Kosten: een minuut of vijf per keer, een kwartier tot een half uur per week.  Navraag leerde dat de mensen met kennis van deze software deze niet kunnen aanpassen.  Dus heb een scriptje geschreven dat de PDF naar mijn eigen website synct via ssh en de datum ernaast aanpast.  Kosten: eenmalig een kwartier en daarna steeds een paar seconden (waarin ik iets anders kan doen, dus netto nul).

Ik snap ook wel dat FOSS niet de oplossing is voor alles en iedereen.  Maar laten we proberen onze hoger opgeleiden kritisch te leren nadenken in plaats van te hersenspoelen, zodat ze zelf keuzes kunnen maken en niet met hun diploma nog in de hand al 10-0 achterstaan.  En laten we die handige ICT-ers dan vervolgens gebruiken om goede ICT-systemen op te zetten, die ervoor zorgen dat alle randverschijnselen in onderwijsland wat gladder verlopen, zodat we onze studenten nóg beter kunnen opleiden.  Een soort omgekeerde vicieuze cirkel dus.


[fn:1] In werkelijkheid wordt er zelfs helemaal niet vermeld dát er überhaupt keuze is.

[fn:2] Ik weet niet zeker of er nog andere softwareleveranciers in Redmond zijn, maar op een bevolking van 72.000 zielen moet dat haast wel, en het lijkt me sterk dat die slechtere producten leveren dan Microsoft.

[fn:3] Ook al draait dat op slechts een handjevol van de circa 100 veelgebruikte OSs.

[fn:4] Zodat ik al meer dan een jaar niet fatsoenlijk bij mijn email kan, want "IMAP, POP3 en SMTP zijn onveilig"!

[fn:5] Toegegeven, van Teams is een binaryversie beschikbaar die werkt onder Linux.  Het heeft niet alle functies, en nog niet overal is het search and replace van "Skype" naar "Teams" in de broncode gelukt.  Zo zegt mijn Linux-systeem "Skype is using your microphone", ook als ik niet in een Teamsvergadering zit.  Programma afsluiten dus na gebruik!
